/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Booking = {
  _id: string;
  _type: "booking";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  userEmail?: string;
  classSession?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "classSession";
  };
  status?: "confirmed" | "cancelled" | "attended" | "noShow";
  createdAt?: string;
  cancelledAt?: string;
  attendedAt?: string;
};

export type ClassSession = {
  _id: string;
  _type: "classSession";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  activity?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "activity";
  };
  venue?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "venue";
  };
  startTime?: string;
  maxCapacity?: number;
  status?: "scheduled" | "cancelled" | "completed";
};

export type Activity = {
  _id: string;
  _type: "activity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  instructor?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  duration?: number;
  tierLevel?: "basic" | "performance" | "champion";
  price?: number;
  aiKeywords?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  icon?: string;
};

export type Venue = {
  _id: string;
  _type: "venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  address?: {
    fullAddress?: string;
    street?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  location?: Geopoint;
  amenities?: Array<string>;
  openingHours?: Array<{
    day?: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
    open?: string;
    close?: string;
    _key: string;
  }>;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes = Booking | ClassSession | Activity | SanityImageCrop | SanityImageHotspot | Slug | Category | Venue | Geopoint | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: UPCOMING_SESSIONS_QUERY
// Query: *[  _type == "classSession"  && startTime > now()  && status == "scheduled"] | order(startTime asc) {  _id,  startTime,  maxCapacity,  status,  "currentBookings": count(*[    _type == "booking"     && classSession._ref == ^._id     && status == "confirmed"  ]),  activity->{    _id,    name,    slug,    instructor,    duration,    tierLevel,    "image": images[0]  },  venue->{    _id,    name,    slug,    "city": address.city  }}
export type UPCOMING_SESSIONS_QUERYResult = Array<{
  _id: string;
  startTime: string | null;
  maxCapacity: number | null;
  status: "cancelled" | "completed" | "scheduled" | null;
  currentBookings: number;
  activity: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    instructor: string | null;
    duration: number | null;
    tierLevel: "basic" | "champion" | "performance" | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    } | null;
  } | null;
  venue: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    city: string | null;
  } | null;
}>;
// Variable: SESSION_BY_ID_QUERY
// Query: *[  _type == "classSession"  && _id == $sessionId][0]{  _id,  startTime,  maxCapacity,  status,  "currentBookings": count(*[    _type == "booking"     && classSession._ref == ^._id     && status == "confirmed"  ]),  activity->{    _id,    name,    slug,    instructor,    duration,    tierLevel,    description,    images,    category->{      _id,      name,      slug    }  },  venue->{    _id,    name,    slug,    description,    images,    address,    location,    amenities  }}
export type SESSION_BY_ID_QUERYResult = {
  _id: string;
  startTime: string | null;
  maxCapacity: number | null;
  status: "cancelled" | "completed" | "scheduled" | null;
  currentBookings: number;
  activity: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    instructor: string | null;
    duration: number | null;
    tierLevel: "basic" | "champion" | "performance" | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    category: {
      _id: string;
      name: string | null;
      slug: Slug | null;
    } | null;
  } | null;
  venue: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    description: string | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    address: {
      fullAddress?: string;
      street?: string;
      city?: string;
      postcode?: string;
      country?: string;
    } | null;
    location: Geopoint | null;
    amenities: Array<string> | null;
  } | null;
} | null;
// Variable: SESSIONS_BY_ACTIVITY_QUERY
// Query: *[  _type == "classSession"  && activity._ref == $activityId  && startTime > now()  && status == "scheduled"] | order(startTime asc) {  _id,  startTime,  maxCapacity,  status,  "currentBookings": count(*[    _type == "booking"     && classSession._ref == ^._id     && status == "confirmed"  ]),  venue->{    _id,    name,    slug,    "city": address.city  }}
export type SESSIONS_BY_ACTIVITY_QUERYResult = Array<{
  _id: string;
  startTime: string | null;
  maxCapacity: number | null;
  status: "cancelled" | "completed" | "scheduled" | null;
  currentBookings: number;
  venue: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    city: string | null;
  } | null;
}>;
// Variable: ACTIVITIES_QUERY
// Query: *[  _type == "activity"] | order(name asc) {  _id,  name,  slug,  instructor,  duration,  tierLevel,  "image": images[0],  category->{    _id,    name,    slug  }}
export type ACTIVITIES_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  instructor: string | null;
  duration: number | null;
  tierLevel: "basic" | "champion" | "performance" | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | null;
  category: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
}>;
// Variable: ACTIVITY_BY_SLUG_QUERY
// Query: *[  _type == "activity"  && slug.current == $slug][0]{  _id,  name,  slug,  instructor,  duration,  tierLevel,  description,  images,  price,  aiKeywords,  category->{    _id,    name,    slug  }}
export type ACTIVITY_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  instructor: string | null;
  duration: number | null;
  tierLevel: "basic" | "champion" | "performance" | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number | null;
  aiKeywords: Array<string> | null;
  category: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
} | null;
// Variable: CATEGORIES_QUERY
// Query: *[  _type == "category"] | order(name asc) {  _id,  name,  slug,  description,  icon}
export type CATEGORIES_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  icon: string | null;
}>;
// Variable: VENUES_QUERY
// Query: *[  _type == "venue"] | order(name asc) {  _id,  name,  slug,  description,  "image": images[0],  address,  location,  amenities}
export type VENUES_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | null;
  address: {
    fullAddress?: string;
    street?: string;
    city?: string;
    postcode?: string;
    country?: string;
  } | null;
  location: Geopoint | null;
  amenities: Array<string> | null;
}>;
// Variable: VENUE_BY_SLUG_QUERY
// Query: *[  _type == "venue"  && slug.current == $slug][0]{  _id,  name,  slug,  description,  images,  address,  location,  amenities,  openingHours}
export type VENUE_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  address: {
    fullAddress?: string;
    street?: string;
    city?: string;
    postcode?: string;
    country?: string;
  } | null;
  location: Geopoint | null;
  amenities: Array<string> | null;
  openingHours: Array<{
    day?: "friday" | "monday" | "saturday" | "sunday" | "thursday" | "tuesday" | "wednesday";
    open?: string;
    close?: string;
    _key: string;
  }> | null;
} | null;
// Variable: USER_BOOKINGS_QUERY
// Query: *[  _type == "booking"  && clerkUserId == $userId] | order(classSession->startTime desc) {  _id,  status,  createdAt,  attendedAt,  cancelledAt,  classSession->{    _id,    startTime,    activity->{      _id,      name,      slug,      duration,      "image": images[0]    },    venue->{      _id,      name,      "city": address.city    }  }}
export type USER_BOOKINGS_QUERYResult = Array<{
  _id: string;
  status: "attended" | "cancelled" | "confirmed" | "noShow" | null;
  createdAt: string | null;
  attendedAt: string | null;
  cancelledAt: string | null;
  classSession: {
    _id: string;
    startTime: string | null;
    activity: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      duration: number | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      } | null;
    } | null;
    venue: {
      _id: string;
      name: string | null;
      city: string | null;
    } | null;
  } | null;
}>;
// Variable: USER_UPCOMING_BOOKINGS_QUERY
// Query: *[  _type == "booking"  && clerkUserId == $userId  && status == "confirmed"  && classSession->startTime > now()] | order(classSession->startTime asc) {  _id,  status,  createdAt,  classSession->{    _id,    startTime,    activity->{      _id,      name,      slug,      duration,      "image": images[0]    },    venue->{      _id,      name,      "city": address.city    }  }}
export type USER_UPCOMING_BOOKINGS_QUERYResult = Array<{
  _id: string;
  status: "attended" | "cancelled" | "confirmed" | "noShow" | null;
  createdAt: string | null;
  classSession: {
    _id: string;
    startTime: string | null;
    activity: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      duration: number | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      } | null;
    } | null;
    venue: {
      _id: string;
      name: string | null;
      city: string | null;
    } | null;
  } | null;
}>;
// Variable: VENUES_WITH_SESSIONS_QUERY
// Query: *[  _type == "venue"  && count(*[    _type == "classSession"    && venue._ref == ^._id    && startTime > now()    && status == "scheduled"  ]) > 0] {  _id,  name,  slug,  location,  "upcomingSessionsCount": count(*[    _type == "classSession"    && venue._ref == ^._id    && startTime > now()    && status == "scheduled"  ])}
export type VENUES_WITH_SESSIONS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  location: Geopoint | null;
  upcomingSessionsCount: number;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[\n  _type == \"classSession\"\n  && startTime > now()\n  && status == \"scheduled\"\n] | order(startTime asc) {\n  _id,\n  startTime,\n  maxCapacity,\n  status,\n  \"currentBookings\": count(*[\n    _type == \"booking\" \n    && classSession._ref == ^._id \n    && status == \"confirmed\"\n  ]),\n  activity->{\n    _id,\n    name,\n    slug,\n    instructor,\n    duration,\n    tierLevel,\n    \"image\": images[0]\n  },\n  venue->{\n    _id,\n    name,\n    slug,\n    \"city\": address.city\n  }\n}": UPCOMING_SESSIONS_QUERYResult;
    "*[\n  _type == \"classSession\"\n  && _id == $sessionId\n][0]{\n  _id,\n  startTime,\n  maxCapacity,\n  status,\n  \"currentBookings\": count(*[\n    _type == \"booking\" \n    && classSession._ref == ^._id \n    && status == \"confirmed\"\n  ]),\n  activity->{\n    _id,\n    name,\n    slug,\n    instructor,\n    duration,\n    tierLevel,\n    description,\n    images,\n    category->{\n      _id,\n      name,\n      slug\n    }\n  },\n  venue->{\n    _id,\n    name,\n    slug,\n    description,\n    images,\n    address,\n    location,\n    amenities\n  }\n}": SESSION_BY_ID_QUERYResult;
    "*[\n  _type == \"classSession\"\n  && activity._ref == $activityId\n  && startTime > now()\n  && status == \"scheduled\"\n] | order(startTime asc) {\n  _id,\n  startTime,\n  maxCapacity,\n  status,\n  \"currentBookings\": count(*[\n    _type == \"booking\" \n    && classSession._ref == ^._id \n    && status == \"confirmed\"\n  ]),\n  venue->{\n    _id,\n    name,\n    slug,\n    \"city\": address.city\n  }\n}": SESSIONS_BY_ACTIVITY_QUERYResult;
    "*[\n  _type == \"activity\"\n] | order(name asc) {\n  _id,\n  name,\n  slug,\n  instructor,\n  duration,\n  tierLevel,\n  \"image\": images[0],\n  category->{\n    _id,\n    name,\n    slug\n  }\n}": ACTIVITIES_QUERYResult;
    "*[\n  _type == \"activity\"\n  && slug.current == $slug\n][0]{\n  _id,\n  name,\n  slug,\n  instructor,\n  duration,\n  tierLevel,\n  description,\n  images,\n  price,\n  aiKeywords,\n  category->{\n    _id,\n    name,\n    slug\n  }\n}": ACTIVITY_BY_SLUG_QUERYResult;
    "*[\n  _type == \"category\"\n] | order(name asc) {\n  _id,\n  name,\n  slug,\n  description,\n  icon\n}": CATEGORIES_QUERYResult;
    "*[\n  _type == \"venue\"\n] | order(name asc) {\n  _id,\n  name,\n  slug,\n  description,\n  \"image\": images[0],\n  address,\n  location,\n  amenities\n}": VENUES_QUERYResult;
    "*[\n  _type == \"venue\"\n  && slug.current == $slug\n][0]{\n  _id,\n  name,\n  slug,\n  description,\n  images,\n  address,\n  location,\n  amenities,\n  openingHours\n}": VENUE_BY_SLUG_QUERYResult;
    "*[\n  _type == \"booking\"\n  && clerkUserId == $userId\n] | order(classSession->startTime desc) {\n  _id,\n  status,\n  createdAt,\n  attendedAt,\n  cancelledAt,\n  classSession->{\n    _id,\n    startTime,\n    activity->{\n      _id,\n      name,\n      slug,\n      duration,\n      \"image\": images[0]\n    },\n    venue->{\n      _id,\n      name,\n      \"city\": address.city\n    }\n  }\n}": USER_BOOKINGS_QUERYResult;
    "*[\n  _type == \"booking\"\n  && clerkUserId == $userId\n  && status == \"confirmed\"\n  && classSession->startTime > now()\n] | order(classSession->startTime asc) {\n  _id,\n  status,\n  createdAt,\n  classSession->{\n    _id,\n    startTime,\n    activity->{\n      _id,\n      name,\n      slug,\n      duration,\n      \"image\": images[0]\n    },\n    venue->{\n      _id,\n      name,\n      \"city\": address.city\n    }\n  }\n}": USER_UPCOMING_BOOKINGS_QUERYResult;
    "*[\n  _type == \"venue\"\n  && count(*[\n    _type == \"classSession\"\n    && venue._ref == ^._id\n    && startTime > now()\n    && status == \"scheduled\"\n  ]) > 0\n] {\n  _id,\n  name,\n  slug,\n  location,\n  \"upcomingSessionsCount\": count(*[\n    _type == \"classSession\"\n    && venue._ref == ^._id\n    && startTime > now()\n    && status == \"scheduled\"\n  ])\n}": VENUES_WITH_SESSIONS_QUERYResult;
  }
}
